### ISSUE TITLE
Use of deprecated Any::Moose

### ISSUE THREAD

**Issue by karenetheridge** [sherwind/Data-Password-passwdqc#1]
As documented, this is now deprecated in favour of Moo.

see http://shadow.cat/blog/matt-s-trout/moo-versus-any-moose/ for an explanation of why Any::Moose is broken by design.

https://metacpan.org/pod/Any::Moose#DEPRECATION
日本語翻訳: http://blog.64p.org/entry/2013/02/06/094906

**Comment by sherwind** [comment]
Thanks. It's already fixed in the version released to CPAN. :-)

**Comment by karenetheridge** [comment]
woohoo!
